package de.husst.pkm;

public class H2PConstants {
	
	// ID offsets
    public static final int ID_ORTSPUNKT_OFFSET = 1000000;
    public static final int ID_RELCODE_OFFSET = 2000000;
	public static final int ID_TARIFRELEVANTERPUNKT_OFFSET = 3000000;
	
    // Pool Constants
    public static final int POOL_ID_AUSGANGSKONTEXT_SORTE_BEZEICHNUNG = 1;
    public static final int POOL_ID_AUSGANGSKONTEXT_SORTE_BEZEICHNUNG_KURZ = 2;
    public static final int POOL_ID_AUSGANGSKONTEXT_TARIFPUNKT_BEZEICHNUNG = 3;
    public static final int POOL_ID_AUSGANGSKONTEXT_TARIFPUNKT_BEZEICHNUNG_DRUCK = 4;
    public static final int POOL_ID_AUSGANGSKONTEXT_ORTSPUNKT_BEZEICHNUNG = 5;
    public static final int POOL_ID_AUSGANGSKONTEXT_ORTSPUNKT_BEZEICHNUNG_KURZ = 6;
    public static final int POOL_ID_AUSGANGSKONTEXT_ORTSPUNKT_BEZEICHNUNG_DRUCK = 7;
	public static final int POOL_ID_AUSGANGSKONTEXT_VIA_BEZEICHNUNG = 8;
	public static final int POOL_ID_AUSGANGSKONTEXT_VIA_BEZEICHNUNG_DRUCK = 9;
	public static final int POOL_ID_AUSGANGSKONTEXT_TICKET_DRUCK = 10;
    
    public static final int POOL_ID_BEWERTUNGSTYP_ORTSPUNKT_ZU_TARIFRELEVANTERPUNKT = 1;
    public static final int POOL_ID_BEWERTUNGSTYP_RELATIONSCODE_ZU_TARIFPUNKT = 2;
	public static final int POOL_ID_BEWERTUNGSTYP_TARIFRELEVANTERPUNKT_ZU_RELCODE = 0;
    
    public static final int POOL_ID_MODULKONTEXT_HUSST_ENDGERAET=1;
    
    public static final int POOL_ID_WAEHRUNG_EUR=1;

	public static final int POOL_ID_AUSGANGSSCHNITTSTELLE_HUSST_ENDGERAET_STANDARD = 1;
	
	// Datentabelle Nr
    public static final int DATENTABELLE_NR_SORTE_REFEXTERN_TO_PKM_TARIFPRODUKT_NR = 1;
	public static final int DATENTABELLE_NR_ORTSPUNKT_REFEXTERN_TO_PKM_TARIFPUNKT_NR = 2;
	public static final int DATENTABELLE_NR_ORTSPUNKT_IBISCODE_TO_PKM_TARIFPUNKT_NR = 3;
	public static final int DATENTABELLE_NR_ORTSPUNKT_TYP_NR_TO_PKM_TARIFPUNKT_NR = 4;
	public static final int DATENTABELLE_OTPTYP_BEDIENGEBIET_TO_TARIFRELEVANTERPUNKT = 5;
	public static final int DATENTABELLE_RELCODES_START_ZIEL_AUF_TP_START_ZIEL_VIATEXT = 6;
	
	
	public static final int POOL_ID_AUSGANGSPARAMETER_SORTE_BEZEICHNUNG = 10;
	public static final int POOL_ID_AUSGANGSPARAMETER_SORTE_BEZEICHNUNG_KURZ = 11;
	public static final int POOL_ID_AUSGANGSPARAMETER_TARIFPUNKT_START_BEZEICHNUNG = 20;
	public static final int POOL_ID_AUSGANGSPARAMETER_TARIFPUNKT_START_BEZEICHNUNG_DRUCK = 21;
	public static final int POOL_ID_AUSGANGSPARAMETER_ORTSPUNKT_START_BEZEICHNUNG = 30;
	public static final int POOL_ID_AUSGANGSPARAMETER_ORTSPUNKT_START_BEZEICHNUNG_KURZ = 31;
	public static final int POOL_ID_AUSGANGSPARAMETER_ORTSPUNKT_START_BEZEICHNUNG_DRUCK = 32;
	public static final int POOL_ID_AUSGANGSPARAMETER_TARIFPUNKT_ZIEL_BEZEICHNUNG = 40;
	public static final int POOL_ID_AUSGANGSPARAMETER_TARIFPUNKT_ZIEL_BEZEICHNUNG_DRUCK = 41;
	public static final int POOL_ID_AUSGANGSPARAMETER_ORTSPUNKT_ZIEL_BEZEICHNUNG = 50;
	public static final int POOL_ID_AUSGANGSPARAMETER_ORTSPUNKT_ZIEL_BEZEICHNUNG_KURZ = 51;
	public static final int POOL_ID_AUSGANGSPARAMETER_ORTSPUNKT_ZIEL_BEZEICHNUNG_DRUCK = 52;
	public static final int POOL_ID_AUSGANGSPARAMETER_VIA_BEZEICHNUNG = 60;
	public static final int POOL_ID_AUSGANGSPARAMETER_VIA_BEZEICHNUNG_DRUCK = 61;
	public static final int POOL_ID_AUSGANGSPARAMETER_TICKET_SORTEDRUCKTEXT = 70;
	public static final int POOL_ID_AUSGANGSPARAMETER_TICKET_PREIS = 71;
	public static final int POOL_ID_AUSGANGSPARAMETER_TICKET_PREISMWST = 72;
	public static final int POOL_ID_AUSGANGSPARAMETER_TICKET_PREISSTUFENDRUCKTEXT = 73;
	public static final int POOL_ID_AUSGANGSPARAMETER_TICKET_GUELTIKEITSBEGINNDRUCKTEXT = 74;
	public static final int POOL_ID_AUSGANGSPARAMETER_TICKET_GUELTIGKEITSENDEDRUCKTEXT = 75;
	public static final int POOL_ID_AUSGANGSPARAMETER_TICKET_STARTTARIFPUNKTDRUCKTEXT = 76;
	public static final int POOL_ID_AUSGANGSPARAMETER_TICKET_ZIELTARIFPUNKTDRUCKTEXT = 77;
	public static final int POOL_ID_AUSGANGSPARAMETER_TICKET_VIADRUCKTEXT = 78;

	
	public static final int POOL_ID_MODULKONTEXTBEDINGUNG_HUSST_ENDGERAET = 0;
	
	// Identifikationsparameter (HUSST spezifisch ab 100, ansonsten Identifikationsparameter_CODE aus BOM)
	public static final int IDENTIFIKATIONSPARAMETER_SORTENGRUPPE_NR=100; 
	public static final int IDENTIFIKATIONSPARAMETER_TARIFART_NR = 101;
	
	// statische Zuordnungstypen <1000
	public static final int ZUORDNUNGSTYP_TARIFRELEVANTERPUNKT_ZU_RELCODE=1;










}
